name: build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   name: linux
          #   build-script: "build-linux.sh"
          - os: windows-latest
            name: windows
            build-script: "build-windows.ps1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build
        run: "./system/${{ matrix.build-script }} dist-${{ matrix.name }}"
      - name: Zip release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          directory: ./dist-${{ matrix.name }}/
          filename: ${{ github.event.repository.name }}-${{ matrix.name }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist-${{ matrix.name }}/${{ github.event.repository.name }}-${{ matrix.name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: True
          files: ./dist-${{ matrix.name }}/${{ github.event.repository.name }}-${{ matrix.name }}.zip
